import img1 from "../../../assets/293076870_742525037018858_6561026921075834909_n.jpg"
import img2 from "../../../assets/293350364_372270118175081_3046696230036478632_n.jpg"
import img3 from "../../../assets/lelu14.jpg"
import img4 from "../../../assets/301845189_3146127769032460_5176714179471543522_n.jpg"
import img5 from "../../../assets/backpack1.jpg"
import img6 from "../../../assets/backpack2.jpg"
import img7 from "../../../assets/casual1.jpg"
import img8 from "../../../assets/casual2.jpg"
import img9 from "../../../assets/casual3.jpg"
import img10 from "../../../assets/summer2.jpg"
import img11 from "../../../assets/men1.jpg"
import img12 from "../../../assets/men2.jpg"
import img13 from "../../../assets/women1.jpg"
import img14 from "../../../assets/women2.jpg"
import img15 from "../../../assets/women3.jpg"
import img16 from "../../../assets/women4.jpg"
import img17 from "../../../assets/summer1.jpg"
import img18 from "../../../assets/summer2.jpg"
import img19 from "../../../assets/items/bag1.jpg"
import img20 from "../../../assets/items/bag2.jpg"
import img21 from "../../../assets/items/bag3.jpg"
import img22 from "../../../assets/items/bag4.jpg"
import img23 from "../../../assets/items/basic1.jpg"
import img24 from "../../../assets/items/basic2.jpg"
import img25 from "../../../assets/items/basic3.jpg"
import img26 from "../../../assets/items/basic4.jpg"
import img27 from "../../../assets/items/cargo1.jpg"
import img28 from "../../../assets/items/cargo2.jpg"
import img29 from "../../../assets/items/cargo3.jpg"
import img30 from "../../../assets/items/cargo4.jpg"
import img31 from "../../../assets/items/cargo5.jpg"
import img32 from "../../../assets/items/triple1.jpg"
import img33 from "../../../assets/items/triple2.jpg"
import img34 from "../../../assets/items/triple3.jpg"
import img35 from "../../../assets/items/triple4.jpg"
import img36 from "../../../assets/items/triple5.jpg"
import img37 from "../../../assets/items/triple6.jpg"
import img38 from "../../../assets/items/short1.jpg"
import img39 from "../../../assets/items/short2.jpg"
import img40 from "../../../assets/items/short3.jpg"
import img41 from "../../../assets/items/short4.jpg"
import img42 from "../../../assets/items/short5.jpg"
import img43 from "../../../assets/items/short6.jpg"



const Data = [
    {
        id: 1,
        img: img1,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Navy Blue Summer Shirt ",
        price: 500,
        category: "Backpack",
        description: "Introducing our Navy Blue Summer Shirt, the perfect addition to your warm-weather wardrobe. Crafted with care and style in mind, this shirt combines comfort, versatility, and a touch of sophistication. Made from lightweight and breathable fabric, this navy blue shirt keeps you cool and comfortable even on the hottest days. Its relaxed fit allows for easy movement and a laid-back look, making it suitable for both casual outings and more formal occasions.  The navy blue color adds a timeless appeal to this shirt, offering a versatile option that pairs well with a variety of bottoms.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 2,
        img: img2,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Navy Blue Summer Shirt ",
        price: 500,
        category: "Backpack",
        description: "Introducing our Navy Blue Summer Shirt, the perfect addition to your warm-weather wardrobe. Crafted with care and style in mind, this shirt combines comfort, versatility, and a touch of sophistication. Made from lightweight and breathable fabric, this navy blue shirt keeps you cool and comfortable even on the hottest days. Its relaxed fit allows for easy movement and a laid-back look, making it suitable for both casual outings and more formal occasions.  The navy blue color adds a timeless appeal to this shirt, offering a versatile option that pairs well with a variety of bottoms.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 3,
        img: img3,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Navy Blue Summer Shirt ",
        price: 600,
        category: "Backpack",
        description: "Introducing our Navy Blue Summer Shirt, the perfect addition to your warm-weather wardrobe. Crafted with care and style in mind, this shirt combines comfort, versatility, and a touch of sophistication. Made from lightweight and breathable fabric, this navy blue shirt keeps you cool and comfortable even on the hottest days. Its relaxed fit allows for easy movement and a laid-back look, making it suitable for both casual outings and more formal occasions.  The navy blue color adds a timeless appeal to this shirt, offering a versatile option that pairs well with a variety of bottoms.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 4,
        img: img4,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Hawaiian Summer Shirt",
        price: 500,
        category: "Shirt",
        description: " Introducing our Hawaiian Summer Shirt, the ultimate tropical statement piece for your summer wardrobe. This vibrant and stylish shirt brings the spirit of the islands to life with its eye-catching patterns and relaxed fit. Crafted from lightweight and breathable fabric, it keeps you cool and comfortable in the heat. Embrace the laid-back vibes of summer with this must-have shirt that effortlessly captures the essence of paradise. Get ready to turn heads and make a bold fashion statement with our Hawaiian Summer Shirt.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["Shirt ", "Summer", "Vivid"],
    },
    {
        id: 5,
        img: img5,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Retro Backpack",
        price: 600,
        category: "Backpack",
        description: "Introducing our Retro Backpack, a nostalgic blend of style and functionality. This backpack takes inspiration from the classic designs of the past while incorporating modern features for everyday convenience. Its durable construction and spacious compartments make it perfect for carrying your essentials in retro-inspired fashion. The timeless appeal of the Retro Backpack makes it a versatile accessory, suitable for both work and play. With its vintage charm and practicality, this backpack is sure to become your go-to companion for any adventure. Upgrade your accessory game with the Retro Backpack and relive the golden era of backpack fashion.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 6,
        img: img6,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Retro Backpack",
        price: 600,
        category: "Backpack",
        description: "Introducing our Retro Backpack, a nostalgic blend of style and functionality. This backpack takes inspiration from the classic designs of the past while incorporating modern features for everyday convenience. Its durable construction and spacious compartments make it perfect for carrying your essentials in retro-inspired fashion. The timeless appeal of the Retro Backpack makes it a versatile accessory, suitable for both work and play. With its vintage charm and practicality, this backpack is sure to become your go-to companion for any adventure. Upgrade your accessory game with the Retro Backpack and relive the golden era of backpack fashion.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 7,
        img: img7,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Just Jump T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Introducing the 'Just Jump' Shirt from our latest collection. This shirt is designed for those who dare to take a leap and embrace life's adventures. Made from high-quality fabric, it offers both comfort and style. The vibrant colors and eye-catching graphic on the front perfectly capture the essence of youthful energy and enthusiasm. Whether you're heading to a casual outing or a weekend getaway, this shirt will effortlessly elevate your look. Pair it with jeans or shorts for a laid-back yet trendy ensemble. Join the 'Just Jump' movement and let this shirt inspire you to embrace new experiences with confidence and style.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 8,
        img: img8,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Just Jump T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Introducing the 'Just Jump' Shirt from our latest collection. This shirt is designed for those who dare to take a leap and embrace life's adventures. Made from high-quality fabric, it offers both comfort and style. The vibrant colors and eye-catching graphic on the front perfectly capture the essence of youthful energy and enthusiasm. Whether you're heading to a casual outing or a weekend getaway, this shirt will effortlessly elevate your look. Pair it with jeans or shorts for a laid-back yet trendy ensemble. Join the 'Just Jump' movement and let this shirt inspire you to embrace new experiences with confidence and style.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 9,
        img: img9,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Just Jump T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Introducing the 'Just Jump' Shirt from our latest collection. This shirt is designed for those who dare to take a leap and embrace life's adventures. Made from high-quality fabric, it offers both comfort and style. The vibrant colors and eye-catching graphic on the front perfectly capture the essence of youthful energy and enthusiasm. Whether you're heading to a casual outing or a weekend getaway, this shirt will effortlessly elevate your look. Pair it with jeans or shorts for a laid-back yet trendy ensemble. Join the 'Just Jump' movement and let this shirt inspire you to embrace new experiences with confidence and style.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 10,
        img: img10,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Vibrant Tropical T-Shirt",
        price: 600,
        category: "Printed Shirt",
        description: " Introducing our Vibrant Tropical T-Shirt, a must-have for those who love to embrace the vibrant energy of tropical paradises. This shirt features a captivating print inspired by lush palm trees, exotic flowers, and breathtaking sunsets. Made from soft and breathable fabric, it ensures all-day comfort in any climate. The vibrant colors and intricate details of the tropical design will transport you to an island getaway, even if you're just strolling down the street. Whether you're heading to a beach party, enjoying a summer barbecue, or simply want to infuse your everyday style with a touch of paradise, this Vibrant Tropical T-Shirt is the perfect choice. Pair it with shorts, jeans, or a skirt for a laid-back and trendy look that exudes summer vibes. Embrace the tropical spirit and make a statement with our Vibrant Tropical T-Shirt.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 12,
        img: img12,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "White Silky Shirt",
        price: 800,
        category: "Shirt",
        description: "Introducing our White Silky Shirt, the epitome of elegance and sophistication. Crafted from luxurious and smooth silk fabric, this shirt offers a refined and polished look that is perfect for both formal occasions and upscale events. The pristine white color adds a timeless charm, making it a versatile piece that can be effortlessly styled for various outfits. The silky texture not only feels incredibly comfortable against your skin but also adds a touch of opulence to your ensemble. Whether you're attending a business meeting, a special celebration, or a romantic dinner, this White Silky Shirt is designed to make a lasting impression. Pair it with tailored pants or a skirt for a classic and sophisticated look, or dress it down with jeans for a chic and contemporary twist. Elevate your style with our White Silky Shirt and embrace a refined sense of fashion.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 13,
        img: img13,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Floral Summer Shirt",
        price: 700,
        category: "Summer Shirt",
        description: "Introducing our Floral Summer Shirt, a blooming delight that captures the essence of the season. Designed with vibrant flowers and lush greenery, this shirt brings a burst of color and freshness to your summer wardrobe. The lightweight and breathable fabric ensure optimal comfort, keeping you cool even on the hottest days. The playful floral print adds a touch of whimsy and charm, making it a perfect choice for casual outings, beach trips, or picnics in the park. Pair it with shorts, skirts, or jeans for a versatile and effortlessly stylish look. Whether you're strolling along the shoreline or attending a garden party, this Floral Summer Shirt is guaranteed to turn heads and evoke a sense of joy. Embrace the spirit of summer and bloom with confidence in our Floral Summer Shirt.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 14,
        img: img14,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 15,
        img: img15,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 16,
        img: img16,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Green Tropical T-Shirt",
        price: 600,
        category: "Printed Shirt",
        description: " Introducing our Vibrant Tropical T-Shirt, a must-have for those who love to embrace the vibrant energy of tropical paradises. This shirt features a captivating print inspired by lush palm trees, exotic flowers, and breathtaking sunsets. Made from soft and breathable fabric, it ensures all-day comfort in any climate. The vibrant colors and intricate details of the tropical design will transport you to an island getaway, even if you're just strolling down the street. Whether you're heading to a beach party, enjoying a summer barbecue, or simply want to infuse your everyday style with a touch of paradise, this Vibrant Tropical T-Shirt is the perfect choice. Pair it with shorts, jeans, or a skirt for a laid-back and trendy look that exudes summer vibes. Embrace the tropical spirit and make a statement with our Vibrant Tropical T-Shirt.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 17,
        img: img17,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Green Tropical T-Shirt",
        price: 600,
        category: "Printed Shirt",
        description: " Introducing our Vibrant Tropical T-Shirt, a must-have for those who love to embrace the vibrant energy of tropical paradises. This shirt features a captivating print inspired by lush palm trees, exotic flowers, and breathtaking sunsets. Made from soft and breathable fabric, it ensures all-day comfort in any climate. The vibrant colors and intricate details of the tropical design will transport you to an island getaway, even if you're just strolling down the street. Whether you're heading to a beach party, enjoying a summer barbecue, or simply want to infuse your everyday style with a touch of paradise, this Vibrant Tropical T-Shirt is the perfect choice. Pair it with shorts, jeans, or a skirt for a laid-back and trendy look that exudes summer vibes. Embrace the tropical spirit and make a statement with our Vibrant Tropical T-Shirt.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 18,
        img: img18,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 19,
        img: img19,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 20,
        img: img20,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 21,
        img: img21,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 22,
        img: img22,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 23,
        img: img23,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 24,
        img: img24,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 25,
        img: img25,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 26,
        img: img26,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 27,
        img: img27,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 28,
        img: img28,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 29,
        img: img29,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 30,
        img: img30,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 31,
        img: img31,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 32,
        img: img32,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 33,
        img: img33,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 34,
        img: img34,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 35,
        img: img35,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 36,
        img: img36,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 37,
        img: img37,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, {
        id: 38,
        img: img38,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 39,
        img: img39,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 40,
        img: img40,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 41,
        img: img41,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 41,
        img: img41,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 42,
        img: img42,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 43,
        img: img43,
        img1: img17,
        img2: img18,
        img4: img19,
        img5: img20,
        img6: img21,
        img7: img22,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
];
export default Data;