import img1 from "../../../assets/293076870_742525037018858_6561026921075834909_n.jpg"
import img2 from "../../../assets/293350364_372270118175081_3046696230036478632_n.jpg"
import img3 from "../../../assets/293269097_1116061939288589_4759040072183287974_n.jpg"
import img4 from "../../../assets/301845189_3146127769032460_5176714179471543522_n.jpg"
import img5 from "../../../assets/backpack1.jpg"
import img6 from "../../../assets/backpack2.jpg"
import img7 from "../../../assets/casual1.jpg"
import img8 from "../../../assets/casual2.jpg"
import img9 from "../../../assets/casual3.jpg"
import img10 from "../../../assets/summer2.jpg"
import img11 from "../../../assets/men1.jpg"
import img12 from "../../../assets/men2.jpg"
import img13 from "../../../assets/women1.jpg"
import img14 from "../../../assets/women2.jpg"
import img15 from "../../../assets/women3.jpg"
import img16 from "../../../assets/women4.jpg"
import img17 from "../../../assets/summer1.jpg"
import img18 from "../../../assets/summer2.jpg"
import img19 from "../../../assets/items/bag1.jpg"
import img20 from "../../../assets/items/bag2.jpg"
import img21 from "../../../assets/items/bag3.jpg"
import img22 from "../../../assets/items/bag4.jpg"
import img23 from "../../../assets/items/basic1.jpg"
import img24 from "../../../assets/items/basic2.jpg"
import img25 from "../../../assets/items/basic3.jpg"
import img26 from "../../../assets/items/basic4.jpg"
import img27 from "../../../assets/items/cargo1.jpg"
import img28 from "../../../assets/items/cargo2.jpg"
import img29 from "../../../assets/items/cargo3.jpg"
import img30 from "../../../assets/items/cargo4.jpg"
import img31 from "../../../assets/items/cargo5.jpg"
import img32 from "../../../assets/items/triple1.jpg"
import img33 from "../../../assets/items/triple2.jpg"
import img34 from "../../../assets/items/triple3.jpg"
import img35 from "../../../assets/items/triple4.jpg"
import img36 from "../../../assets/items/triple5.jpg"
import img37 from "../../../assets/items/triple6.jpg"
import img38 from "../../../assets/items/short1.jpg"
import img39 from "../../../assets/items/short2.jpg"
import img40 from "../../../assets/items/short3.jpg"
import img41 from "../../../assets/items/short4.jpg"
import img42 from "../../../assets/items/short5.jpg"
import img43 from "../../../assets/items/short6.jpg"



const Data = [
    {
        id: 1,
        img: img1,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 2,
        img: img2,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 3,
        img: img3,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 4,
        img: img4,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 5,
        img: img5,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 6,
        img: img6,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 7,
        img: img7,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 8,
        img: img8,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 9,
        img: img9,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 10,
        img: img10,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 11,
        img: img11,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 12,
        img: img12,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 13,
        img: img13,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 14,
        img: img14,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 15,
        img: img15,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 16,
        img: img16,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 17,
        img: img17,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 18,
        img: img18,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 19,
        img: img19,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 20,
        img: img20,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 21,
        img: img21,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 22,
        img: img22,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 23,
        img: img23,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 24,
        img: img24,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 25,
        img: img25,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 26,
        img: img26,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 27,
        img: img27,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 28,
        img: img28,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 29,
        img: img29,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 30,
        img: img30,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 31,
        img: img31,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 32,
        img: img32,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 33,
        img: img33,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 34,
        img: img34,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
    {
        id: 35,
        img: img35,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 36,
        img: img36,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 37,
        img: img37,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, {
        id: 38,
        img: img38,
        name: "Summer Dress",
        price: 1500,
        category: "Dress",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["dress ", "summer ", "clothing"],
    },
    {
        id: 39,
        img: img39,
        name: "Men's Jacket",
        price: 2000,
        category: "Jacket",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["jacket ", "men ", "clothing"],
    },
    {
        id: 40,
        img: img40,
        name: "Stylish Backpack",
        price: 1200,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "fashion ", "bag"],
    },
    {
        id: 41,
        img: img41,
        name: "Backpack",
        price: 1000,
        category: "Backpack",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["backpack ", "travel ", "bag"],
    },
    {
        id: 41,
        img: img41,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 42,
        img: img42,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    },
    {
        id: 43,
        img: img43,
        name: "Casual T-Shirt",
        price: 500,
        category: "Shirt",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
        inCart: false,
        count: 0,
        total: 0,
        tags: ["t-shirt ", "casual ", "clothing"],
    }, 
];
export default Data;